### ISSUE TITLE
Only images shoud be allowed to be chosen!!!

### ISSUE THREAD

**Issue by hossshakiba** [mitchtabian/Codingwithmitch-Chat#1]
Hi Mitch and thank u for the useful content you shared. ❤️ 
There seems to be a tricky issue with image uploading. All kinds of files (pdf, docx, py, ....) are able to be uploaded.
They wouldn't make any problems out there and image uploading process wouldn't crash, but it would so better and more user-friendly to not allow them to be chosen in the first place. Any recommendations on how to implement that? or at least, showing an error message after  any wrong choice.
Thx in advance.

**Comment by mitchtabian** [comment]
https://flaviocopes.com/how-to-accept-images-file-input/
